# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SocialApi")

api.instance <- SocialApi$new()

test_that("PhonePrefix", {
  # tests for PhonePrefix
  # [USES 11 UNITS] Infer the likely country and phone prefix, given a personal name and formatted / unformatted phone number.
  # @param first.name 
  # @param last.name 
  # @param phone.number 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNamePhoneCodedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PhonePrefixBatch", {
  # tests for PhonePrefixBatch
  # [USES 11 UNITS] Infer the likely country and phone prefix, of up to 1000 personal names, detecting automatically the local context given a name and formatted / unformatted phone number.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNamePhoneNumberIn] :batch.first.last.name.phone.number.in A list of personal names
  # @return [BatchFirstLastNamePhoneCodedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

