# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PersonalApi")

api.instance <- PersonalApi$new()

test_that("Country", {
  # tests for Country
  # [USES 10 UNITS] Infer the likely country of residence of a personal full name, or one surname. Assumes names as they are in the country of residence OR the country of origin.
  # @param personal.name.full 
  # @param [Hash] opts the optional parameters
  # @return [PersonalNameGeoOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CountryBatch", {
  # tests for CountryBatch
  # [USES 10 UNITS] Infer the likely country of residence of up to 1000 personal full names, or surnames. Assumes names as they are in the country of residence OR the country of origin.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchPersonalNameIn] :batch.personal.name.in A list of personal names
  # @return [BatchPersonalNameGeoOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Diaspora", {
  # tests for Diaspora
  # [USES 20 UNITS] Infer the likely ethnicity/diaspora of a personal name, given a country of residence ISO2 code (ex. US, CA, AU, NZ etc.)
  # @param country.iso2 
  # @param first.name 
  # @param last.name 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameDiasporaedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DiasporaBatch", {
  # tests for DiasporaBatch
  # [USES 20 UNITS] Infer the likely ethnicity/diaspora of up to 1000 personal names, given a country of residence ISO2 code (ex. US, CA, AU, NZ etc.)
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameGeoIn] :batch.first.last.name.geo.in A list of personal names
  # @return [BatchFirstLastNameDiasporaedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Gender", {
  # tests for Gender
  # Infer the likely gender of a name.
  # @param first.name 
  # @param last.name 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenderBatch", {
  # tests for GenderBatch
  # Infer the likely gender of up to 1000 names, detecting automatically the cultural context.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameIn] :batch.first.last.name.in A list of personal names
  # @return [BatchFirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenderFull", {
  # tests for GenderFull
  # Infer the likely gender of a full name, ex. John H. Smith
  # @param full.name 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenderFullBatch", {
  # tests for GenderFullBatch
  # Infer the likely gender of up to 1000 full names, detecting automatically the cultural context.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchPersonalNameIn] :batch.personal.name.in A list of personal names
  # @return [BatchPersonalNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenderFullGeo", {
  # tests for GenderFullGeo
  # Infer the likely gender of a full name, given a local context (ISO2 country code).
  # @param full.name 
  # @param country.iso2 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenderFullGeoBatch", {
  # tests for GenderFullGeoBatch
  # Infer the likely gender of up to 1000 full names, with a given cultural context (country ISO2 code).
  # @param [Hash] opts the optional parameters
  # @option opts [BatchPersonalNameGeoIn] :batch.personal.name.geo.in A list of personal names, with a country ISO2 code
  # @return [BatchPersonalNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenderGeo", {
  # tests for GenderGeo
  # Infer the likely gender of a name, given a local context (ISO2 country code).
  # @param first.name 
  # @param last.name 
  # @param country.iso2 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenderGeoBatch", {
  # tests for GenderGeoBatch
  # Infer the likely gender of up to 1000 names, each given a local context (ISO2 country code).
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameGeoIn] :batch.first.last.name.geo.in A list of names, with country code.
  # @return [BatchFirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Origin", {
  # tests for Origin
  # [USES 10 UNITS] Infer the likely country of origin of a personal name. Assumes names as they are in the country of origin. For US, CA, AU, NZ and other melting-pots : use &#39;diaspora&#39; instead.
  # @param first.name 
  # @param last.name 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameOriginedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("OriginBatch", {
  # tests for OriginBatch
  # [USES 10 UNITS] Infer the likely country of origin of up to 1000 names, detecting automatically the cultural context.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameIn] :batch.first.last.name.in A list of personal names
  # @return [BatchFirstLastNameOriginedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ParsedGenderBatch", {
  # tests for ParsedGenderBatch
  # Infer the likely gender of up to 1000 fully parsed names, detecting automatically the cultural context.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchParsedFullNameIn] :batch.parsed.full.name.in A list of personal names
  # @return [BatchFirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ParsedGenderGeoBatch", {
  # tests for ParsedGenderGeoBatch
  # Infer the likely gender of up to 1000 fully parsed names, detecting automatically the cultural context.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchParsedFullNameGeoIn] :batch.parsed.full.name.geo.in A list of personal names
  # @return [BatchFirstLastNameGenderedOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UsRaceEthnicity", {
  # tests for UsRaceEthnicity
  # [USES 10 UNITS] Infer a US resident&#39;s likely race/ethnicity according to US Census taxonomy.
  # @param first.name 
  # @param last.name 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameUSRaceEthnicityOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UsRaceEthnicityBatch", {
  # tests for UsRaceEthnicityBatch
  # [USES 10 UNITS] Infer up-to 1000 US resident&#39;s likely race/ethnicity according to US Census taxonomy.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameGeoIn] :batch.first.last.name.geo.in A list of personal names
  # @return [BatchFirstLastNameUSRaceEthnicityOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UsRaceEthnicityZIP5", {
  # tests for UsRaceEthnicityZIP5
  # [USES 10 UNITS] Infer a US resident&#39;s likely race/ethnicity according to US Census taxonomy, using (optional) ZIP5 code info.
  # @param first.name 
  # @param last.name 
  # @param zip5.code 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNameUSRaceEthnicityOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UsZipRaceEthnicityBatch", {
  # tests for UsZipRaceEthnicityBatch
  # [USES 10 UNITS] Infer up-to 1000 US resident&#39;s likely race/ethnicity according to US Census taxonomy, with (optional) ZIP code.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameGeoZippedIn] :batch.first.last.name.geo.zipped.in A list of personal names
  # @return [BatchFirstLastNameUSRaceEthnicityOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

