# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AdminApi")

api.instance <- AdminApi$new()

test_that("ApiUsage", {
  # tests for ApiUsage
  # Print current API usage.
  # @param [Hash] opts the optional parameters
  # @return [APIPeriodUsageOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiUsageHistory", {
  # tests for ApiUsageHistory
  # Print historical API usage.
  # @param [Hash] opts the optional parameters
  # @return [APIPeriodUsageOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiUsageHistoryAggregate", {
  # tests for ApiUsageHistoryAggregate
  # Print historical API usage (in an aggregated view, by service, by day/hour/min).
  # @param [Hash] opts the optional parameters
  # @return [APIPeriodUsageOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AvailablePlans", {
  # tests for AvailablePlans
  # List all available plans in the default currency (usd).
  # @param [Hash] opts the optional parameters
  # @return [APIPlansOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AvailablePlans1", {
  # tests for AvailablePlans1
  # List all available plans in the user&#39;s preferred currency.
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIPlansOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AvailableServices", {
  # tests for AvailableServices
  # List of API services and usage cost in Units (default is 1&#x3D;ONE Unit).
  # @param [Hash] opts the optional parameters
  # @return [APIPlansOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BillingCurrencies", {
  # tests for BillingCurrencies
  # List possible currency options for billing (USD, EUR, GBP, ...)
  # @param [Hash] opts the optional parameters
  # @return [CurrenciesOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BillingHistory", {
  # tests for BillingHistory
  # Read the history billing information (invoices paid via Stripe or manually).
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [BillingHistoryOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BillingInfo", {
  # tests for BillingInfo
  # Read the billing information (company name, address, phone, vat ID)
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [BillingInfoInOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Charge", {
  # tests for Charge
  # Create a Stripe Customer, based on a payment card token (from secure StripeJS) and email.
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject] :inline.object 
  # @return [APIKeyOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CorporateKey", {
  # tests for CorporateKey
  # Setting an API Key to a corporate status.
  # @param api.key 
  # @param corporate 
  # @param [Hash] opts the optional parameters
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DebugLevel", {
  # tests for DebugLevel
  # Update debug level for a classifier
  # @param logger 
  # @param level 
  # @param [Hash] opts the optional parameters
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("InvalidateCache", {
  # tests for InvalidateCache
  # Invalidate system caches.
  # @param [Hash] opts the optional parameters
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("NamsorCounter", {
  # tests for NamsorCounter
  # Get the overall API counter
  # @param [Hash] opts the optional parameters
  # @return [SoftwareVersionOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PaymentInfo", {
  # tests for PaymentInfo
  # Get the Stripe payment information associated with the current google auth session token.
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIKeyOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProcureKey", {
  # tests for ProcureKey
  # Procure an API Key (sent via Email), based on an auth token. Keep your API Key secret.
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIKeyOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RedeployUI", {
  # tests for RedeployUI
  # Redeploy UI from current dev branch.
  # @param [Hash] opts the optional parameters
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RedeployUI1", {
  # tests for RedeployUI1
  # Redeploy UI from current dev branch.
  # @param live 
  # @param [Hash] opts the optional parameters
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RemoveUserAccount", {
  # tests for RemoveUserAccount
  # Subscribe to a give API plan, using the user&#39;s preferred or default currency.
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIPlanSubscriptionOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Shutdown", {
  # tests for Shutdown
  # Stop learning and shutdown system.
  # @param [Hash] opts the optional parameters
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SoftwareVersion", {
  # tests for SoftwareVersion
  # Get the current software version
  # @param [Hash] opts the optional parameters
  # @return [SoftwareVersionOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SourceStats", {
  # tests for SourceStats
  # Print basic source statistics.
  # @param source 
  # @param [Hash] opts the optional parameters
  # @return [SystemMetricsOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Stats", {
  # tests for Stats
  # Print basic system statistics.
  # @param [Hash] opts the optional parameters
  # @return [SystemMetricsOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("StripeConnect", {
  # tests for StripeConnect
  # Connects a Stripe Account.
  # @param [Hash] opts the optional parameters
  # @option opts [character] :scope 
  # @option opts [character] :code 
  # @option opts [character] :error 
  # @option opts [character] :error.description 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SubscribePlan", {
  # tests for SubscribePlan
  # Subscribe to a give API plan, using the user&#39;s preferred or default currency.
  # @param plan.name 
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIPlanSubscriptionOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateBillingInfo", {
  # tests for UpdateBillingInfo
  # Sets or update the billing information (company name, address, phone, vat ID)
  # @param token 
  # @param [Hash] opts the optional parameters
  # @option opts [BillingInfoInOut] :billing.info.in.out 
  # @return [BillingInfoInOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateLimit", {
  # tests for UpdateLimit
  # Modifies the hard/soft limit on the API plan&#39;s overages (default is 0$ soft limit).
  # @param usage.limit 
  # @param hard.or.soft 
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIPeriodUsageOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdatePaymentDefault", {
  # tests for UpdatePaymentDefault
  # Update the default Stripe card associated with the current google auth session token.
  # @param defaut.source.id 
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIKeyOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UserInfo", {
  # tests for UserInfo
  # Get the user profile associated with the current google auth session token.
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [APIKeyOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VerifyEmail", {
  # tests for VerifyEmail
  # Verifies an email, based on token sent to that email
  # @param email.token 
  # @param [Hash] opts the optional parameters
  # @return [APIKeyOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VerifyRemoveEmail", {
  # tests for VerifyRemoveEmail
  # Verifies an email, based on token sent to that email
  # @param email.token 
  # @param [Hash] opts the optional parameters
  # @return [APIKeyOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Vet", {
  # tests for Vet
  # Vetting of a source.
  # @param source 
  # @param vetted 
  # @param [Hash] opts the optional parameters
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

