# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChineseApi")

api.instance <- ChineseApi$new()

test_that("ChineseNameCandidates", {
  # tests for ChineseNameCandidates
  # Identify Chinese name candidates, based on the romanized name.
  # @param chinese.surname.latin 
  # @param chinese.given.name.latin 
  # @param [Hash] opts the optional parameters
  # @return [RomanizedNameOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ChineseNameCandidatesBatch", {
  # tests for ChineseNameCandidatesBatch
  # Identify Chinese name candidates, based on the romanized name (firstName &#x3D; chineseGivenName; lastName&#x3D;chineseSurname).
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameIn] :batch.first.last.name.in A list of personal Chinese names in LATIN, firstName &#x3D; chineseGivenName; lastName&#x3D;chineseSurname
  # @return [BatchNameMatchCandidatesOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ChineseNameCandidatesGenderBatch", {
  # tests for ChineseNameCandidatesGenderBatch
  # Identify Chinese name candidates, based on the romanized name (firstName &#x3D; chineseGivenName; lastName&#x3D;chineseSurname).
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNameIn] :batch.first.last.name.in A list of personal Chinese names in LATIN, firstName &#x3D; chineseGivenName; lastName&#x3D;chineseSurname
  # @return [BatchNameMatchCandidatesOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ChineseNameGenderCandidates", {
  # tests for ChineseNameGenderCandidates
  # Identify Chinese name candidates, based on the romanized name - having a known gender (&#39;male&#39; or &#39;female&#39;)
  # @param chinese.surname.latin 
  # @param chinese.given.name.latin 
  # @param known.gender 
  # @param [Hash] opts the optional parameters
  # @return [RomanizedNameOut]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

