# NamSor API v2
#
# NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
#
# OpenAPI spec version: 2.0.2-beta
# Contact: contact@namsor.com
# Generated by: https://openapi-generator.tech

#' @title Social operations
#' @description namsor.Social
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' PhonePrefix [USES 11 UNITS] Infer the likely country and phone prefix, given a personal name and formatted / unformatted phone number.
#'
#'
#' PhonePrefixBatch [USES 11 UNITS] Infer the likely country and phone prefix, of up to 1000 personal names, detecting automatically the local context given a name and formatted / unformatted phone number.
#'
#' }
#'
#' @export
SocialApi <- R6::R6Class(
  'SocialApi',
  public = list(
    userAgent = "OpenAPI-Generator/0.1.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    PhonePrefix = function(first.name, last.name, phone.number, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/api2/json/phoneCode/{firstName}/{lastName}/{phoneNumber}"
      if (!missing(`first.name`)) {
        urlPath <- gsub(paste0("\\{", "firstName", "\\}"), `first.name`, urlPath)
      }

      if (!missing(`last.name`)) {
        urlPath <- gsub(paste0("\\{", "lastName", "\\}"), `last.name`, urlPath)
      }

      if (!missing(`phone.number`)) {
        urlPath <- gsub(paste0("\\{", "phoneNumber", "\\}"), `phone.number`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        FirstLastNamePhoneCodedOut$new()$fromJSONString(httr::content(resp, "text", encoding = "UTF-8"))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }

    },
    PhonePrefixBatch = function(batch.first.last.name.phone.number.in, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`batch.first.last.name.phone.number.in`)) {
        body <- `batch.first.last.name.phone.number.in`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/api2/json/phoneCodeBatch"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        BatchFirstLastNamePhoneCodedOut$new()$fromJSONString(httr::content(resp, "text", encoding = "UTF-8"))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }

    }
  )
)
